version: "3.5"

networks:
  cluster:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.35.4}
    entrypoint: bash
    environment:
      NETWORK: "${NETWORK:-preprod}"
    command: /code/run_node.sh

    networks:
      cluster:
        ipv4_address: 172.20.0.101

    volumes:
      - .:/code
      - node-db:/data/db
      - node-ipc:/ipc
    ports:
      - ${BFT_NODE_PORT:-3000}:3000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  ogmios:
    image: cardanosolutions/ogmios:v5.5.8_1.35.4
    environment:
      NETWORK: "${NETWORK:-preprod}"

    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/code/configs/config.json"
    ]
    volumes:
      - .:/code
      - node-ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  kupo:
    image: cardanosolutions/kupo:v2.3.3
    environment:
      NETWORK: "${NETWORK:-preprod}"

    command: [
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/code/configs/config.json",
      "--host", "0.0.0.0",
      "--since", "origin",
      "--match", "*",
      "--workdir", "/data/kupo/db"
    ]
    volumes:
      - .:/code
      - node-ipc:/ipc
      - kupo-db:/data/kupo/db
    ports:
      - ${KUPO_PORT:-1442}:1442

volumes:
  kupo-db:
  node-db:
  node-ipc:
