# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ dev ]
  # Allows us to run manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      BLOCKFROST_PROJECT_ID: project-id
      BLOCKFROST_API_URL: blockfrost-url
      SNAPSHOTTER_ENDPOINT: snapshotter-endpoint
      PLATFORM_ADDRESS: addr_test1qpcwchvgk3hsasrjnd8a8vmj9upglv82mt0qlsta9vtqzj22vv09xh3ww38qk3tp5yfshhm2qxruyh2hg98wrx7nyh0q9lwnuy
      NETWORK_MODE: TESTNET

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc zlib1g-dev awscli
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov pytest-mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest tests/unit --cov=./src --cov-report=xml
    - name: Upload Test Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN_VOTEAIRE }}
        files: ./coverage.xml
