name: Dev workflow

on: [pull_request]

jobs:
  build:
    env:
      NETWORK_MODE: TESTNET
      PLATFORM_ADDRESS: "addr_test1qpcwchvgk3hsasrjnd8a8vmj9upglv82mt0qlsta9vtqzj22vv09xh3ww38qk3tp5yfshhm2qxruyh2hg98wrx7nyh0q9lwnuy"
      SNAPSHOTTER_ENDPOINT: snapshotter
      BLOCKFROST_PROJECT_ID: key
      BLOCKFROST_API_URL: url
      DB_CONN: sqlite:///
      LABEL: 1916
      LOGLEVEL: INFO
    runs-on: ubuntu-latest
    name: Test dev branch
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Run tests and collect coverage
        run: pytest tests/unit --cov=./src --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.VOTEAIRE_ENGINE_CODECOV_TOKEN }}
          files: ./coverage.xml
